# YAML Linting Configuration
extends: default

# Ignore infrastructure templates with special formatting
ignore: |
  skills/cloud-native/service-mesh/templates/*.yaml
  skills/cloud-native/serverless/templates/*.yaml
  skills/cloud-native/aws-advanced/templates/*.yaml
  skills/cloud-native/kubernetes/templates/*.yaml
  skills/security/api-security/templates/openapi-security.yaml
  skills/security/zero-trust/templates/network-policy.yaml
  skills/devops/monitoring-observability/config/*.yml

rules:
  line-length:
    max: 120
    level: warning

  truthy:
    allowed-values: ['true', 'false', 'on', 'off']

  comments:
    min-spaces-from-content: 2

  indentation:
    spaces: 2
    indent-sequences: true

  brackets:
    max-spaces-inside: 1

  braces:
    max-spaces-inside: 1

  colons:
    max-spaces-after: 1

  commas:
    max-spaces-after: 1

  # Allow some flexibility for readability
  empty-lines:
    max: 2
    max-start: 0
    max-end: 1

  # Don't require document start marker
  document-start: disable

  # Allow quoted strings when needed
  quoted-strings:
    quote-type: any
    required: false
