# Pre-commit hooks for secrets detection
# Install: pre-commit install
# Run: pre-commit run --all-files

repos:
  # Detect secrets
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: 
          - '--baseline'
          - '.secrets.baseline'
          - '--exclude-files'
          - '.*\.md$'

  # Git secrets (AWS keys, etc.)
  - repo: https://github.com/awslabs/git-secrets
    rev: master
    hooks:
      - id: git-secrets
        entry: git-secrets --scan
        language: system

  # Gitleaks
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.0
    hooks:
      - id: gitleaks
        args:
          - --verbose
          - --redact

  # TruffleHog
  - repo: https://github.com/trufflesecurity/trufflehog
    rev: v3.63.0
    hooks:
      - id: trufflehog
        args:
          - filesystem
          - --directory=.
          - --fail
