# SwiftLint Configuration for Standards Repository
# Based on: https://realm.github.io/SwiftLint/

# Excluded paths
excluded:
  - Pods
  - .build
  - .swiftpm
  - DerivedData
  - Tests/LinuxMain.swift
  - Tests/**/XCTestManifests.swift

# Enabled opt-in rules
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - empty_collection_literal
  - empty_count
  - empty_string
  - explicit_init
  - fatal_error_message
  - first_where
  - flatmap_over_map_reduce
  - implicit_return
  - joined_default_parameter
  - last_where
  - literal_expression_end_indentation
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Disabled rules
disabled_rules:
  - todo
  - trailing_whitespace

# Line length
line_length:
  warning: 120
  error: 200
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

# File length
file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

# Function body length
function_body_length:
  warning: 50
  error: 100

# Function parameter count
function_parameter_count:
  warning: 5
  error: 8

# Type body length
type_body_length:
  warning: 300
  error: 500

# Cyclomatic complexity
cyclomatic_complexity:
  warning: 10
  error: 20
  ignores_case_statements: true

# Nesting depth
nesting:
  type_level:
    warning: 2
    error: 3
  statement_level:
    warning: 5
    error: 8

# Identifier names
identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - x
    - y
    - z
    - i
    - j
    - k

# Type name
type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 50
    error: 60
  excluded:
    - ID

# Custom rules
custom_rules:
  # Prefer weak self in closures
  weak_self_in_closure:
    name: "Weak Self in Closure"
    regex: '\{\s*\[.*self.*\]\s+.*in'
    match_kinds:
      - comment
    message: "Consider using [weak self] or [unowned self] in closures to avoid retain cycles"
    severity: warning

  # Avoid force unwrapping
  no_force_unwrap:
    name: "Force Unwrapping"
    regex: '!\s*(?!\/\/|\/\*)'
    message: "Avoid force unwrapping. Use optional binding or nil coalescing instead"
    severity: warning

  # Require explicit access control
  explicit_access_control:
    name: "Explicit Access Control"
    regex: '(class|struct|enum|protocol|func|var|let)\s+\w+'
    message: "Use explicit access control (private, internal, public, open)"
    severity: warning
    
# Reporter
reporter: "xcode"
