title: "[DISCUSS] "
body: |
  # General Discussion

  ## Topic
  <!-- What would you like to discuss? -->

  ## Context
  <!-- Background information that helps frame the discussion -->

  ## Key Questions
  <!-- Specific questions you'd like community input on -->

  ## Your Perspective
  <!-- Your thoughts, opinions, or preliminary ideas -->

  ## Community Input Needed
  <!-- What kind of feedback or input are you looking for? -->

  ## Related Resources
  <!-- Links to relevant standards, documentation, or external resources -->

labels: ["discussion"]
assignees: []
