title: "[SHOWCASE] "
body: |
  # Community Showcase

  ## What You've Built/Implemented
  <!-- Description of your implementation -->

  ## Standards Used
  <!-- Which standards from this repository did you implement? -->

  ## Implementation Details
  <!-- Technical details about your implementation -->

  ## Challenges Overcome
  <!-- What challenges did you face and how did you solve them? -->

  ## Results and Benefits
  <!-- What were the outcomes? How did the standards help? -->

  ## Lessons Learned
  <!-- What would you do differently? What insights did you gain? -->

  ## Code/Examples (Optional)
  <!-- Links to code repositories, examples, or demos -->

  ## Community Value
  <!-- How might this help others? What can the community learn? -->

labels: ["showcase", "success-story"]
assignees: []
