# Kong API Gateway Security Configuration
# NIST Controls: SC-8, SC-13, IA-5, AC-7

_format_version: "3.0"

services:
  - name: secure-api
    url: http://backend:8000
    protocol: https
    port: 443

    plugins:
      # Rate limiting
      - name: rate-limiting
        config:
          minute: 100
          hour: 1000
          policy: redis
          redis_host: redis
          redis_port: 6379
          fault_tolerant: true

      # Authentication
      - name: jwt
        config:
          key_claim_name: kid
          secret_is_base64: false
          maximum_expiration: 3600

      # CORS
      - name: cors
        config:
          origins:
            - https://app.example.com
          methods:
            - GET
            - POST
            - PUT
            - DELETE
          headers:
            - Authorization
            - Content-Type
          exposed_headers:
            - X-Total-Count
          credentials: true
          max_age: 3600

      # Request validation
      - name: request-validator
        config:
          body_schema: |
            {
              "type": "object",
              "additionalProperties": false
            }

      # IP restriction
      - name: ip-restriction
        config:
          allow:
            - 10.0.0.0/8
            - 192.168.0.0/16

      # Request size limit
      - name: request-size-limiting
        config:
          allowed_payload_size: 10

      # Bot detection
      - name: bot-detection
        config:
          allow:
            - googlebot
          deny:
            - scrapy

    routes:
      - name: api-route
        paths:
          - /api/v2
        strip_path: true

        plugins:
          # Route-specific rate limit
          - name: rate-limiting
            config:
              minute: 50

# Global plugins
plugins:
  - name: correlation-id
    config:
      header_name: X-Request-ID
      generator: uuid
      echo_downstream: true

  - name: prometheus
    config:
      per_consumer: true
