source "https://rubygems.org"

# Use the GitHub Pages gem group for compatibility
gem "github-pages", "~> 232", group: :jekyll_plugins
gem "webrick", "~> 1.8"

# Additional plugins
group :jekyll_plugins do
  gem "jekyll-feed"
  gem "jekyll-seo-tag"
  gem "jekyll-sitemap"
  gem "jekyll-relative-links"
  gem "jemoji"
end

# For HTML validation
gem "html-proofer", "~> 5.0", group: :test