---
name: Auto-Fix Trailing Whitespace

'on':
  workflow_dispatch:
    inputs:
      commit_message:
        description: Commit message for whitespace fixes
        required: false
        default: 'fix: remove trailing whitespace from all files'
  schedule:
    # Run weekly on Sunday at 2 AM UTC
    - cron: 0 2 * * 0

permissions:
  contents: write
  pull-requests: write

jobs:
  fix-whitespace:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Run whitespace fix script
        id: fix
        run: |
          # Make script executable
          chmod +x scripts/fix_trailing_whitespace.sh

          # Run the fix script and capture output
          output=$(./scripts/fix_trailing_whitespace.sh 2>&1)
          echo "$output"

          # Check if any files were modified
          if git diff --quiet; then
            echo "No whitespace issues found"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "Whitespace issues fixed"
            echo "has_changes=true" >> $GITHUB_OUTPUT
            # Get list of modified files
            echo "modified_files<<EOF" >> $GITHUB_OUTPUT
            git diff --name-only >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.fix.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: |
            ${{ github.event.inputs.commit_message || 'fix: remove trailing whitespace from all files' }}

            Automated fix for trailing whitespace in:
            ${{ steps.fix.outputs.modified_files }}
          branch: auto-fix/trailing-whitespace
          delete-branch: true
          title: 'fix: remove trailing whitespace'
          body: |
            ## 🤖 Automated Trailing Whitespace Fix

            This PR automatically removes trailing whitespace from all text files in the repository.

            ### Files Modified
            ```
            ${{ steps.fix.outputs.modified_files }}
            ```

            ### Why This Matters
            - Improves code consistency
            - Reduces diff noise in future changes
            - Follows best practices for text files
            - Prevents IDE/editor conflicts

            ---
            *This PR was automatically generated by the whitespace fix workflow.*
          labels: |
            automated
            formatting
            maintenance
          assignees: ${{ github.actor }}
          reviewers: ${{ github.actor }}

      - name: Auto-merge PR (if no changes to code files)
        if: steps.fix.outputs.has_changes == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Wait for PR to be created
          sleep 5

          # Check if only documentation/config files were modified
          modified_files="${{ steps.fix.outputs.modified_files }}"
          code_files_modified=false

          while IFS= read -r file; do
            case "$file" in
              *.py|*.js|*.ts|*.go|*.java|*.c|*.cpp|*.rs)
                code_files_modified=true
                break
                ;;
            esac
          done <<< "$modified_files"

          if [ "$code_files_modified" = false ]; then
            # Auto-merge if only non-code files were modified
            pr_number=$(gh pr list --head auto-fix/trailing-whitespace --json number -q '.[0].number')
            if [ -n "$pr_number" ]; then
              echo "Auto-merging PR #$pr_number (only non-code files modified)"
              gh pr merge "$pr_number" --auto --merge
            fi
          else
            echo "Code files were modified - manual review required"
          fi
