name: Community Feedback Collection

on:
  schedule:
    # Run quarterly on the 1st day of Jan, Apr, Jul, Oct at 10 AM UTC
    - cron: '0 10 1 1,4,7,10 *'
  workflow_dispatch: # Allow manual triggering
    inputs:
      feedback_type:
        description: 'Type of feedback to collect'
        required: true
        default: 'quarterly'
        type: choice
        options:
          - quarterly
          - post_contribution
          - exit_interview
          - feature_request

jobs:
  collect-feedback:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate feedback survey
        id: generate-survey
        uses: actions/github-script@v7
        with:
          script: |
            const feedbackType = '${{ github.event.inputs.feedback_type || 'quarterly' }}';
            const { owner, repo } = context.repo;
            
            let surveyTitle = '';
            let surveyBody = '';
            let labels = ['feedback', 'community'];
            
            const currentDate = new Date();
            const quarter = Math.ceil((currentDate.getMonth() + 1) / 3);
            const year = currentDate.getFullYear();
            
            if (feedbackType === 'quarterly') {
              surveyTitle = `📊 Q${quarter} ${year} Community Feedback Survey`;
              labels.push('quarterly-survey');
              
              surveyBody = `
            # Quarterly Community Feedback Survey - Q${quarter} ${year}
            
            Help us improve the Standards Repository community experience!
            
            ## About This Survey
            
            Your feedback is essential for building a better community and improving our standards. 
            This survey takes 5-10 minutes and helps us understand:
            - How well we're serving the community
            - What improvements are needed
            - What new features or content would be valuable
            - How to better support contributors and users
            
            ## How to Participate
            
            **Option 1: Comment on this issue** with your responses to the questions below
            **Option 2: Create a new discussion** using the feedback template
            **Option 3: Email feedback** to the maintainers (for private feedback)
            
            ## Survey Questions
            
            ### Community Experience
            
            1. **How would you rate your overall experience with the Standards Repository?**
               - [ ] Excellent (5/5)
               - [ ] Good (4/5)
               - [ ] Average (3/5)
               - [ ] Below Average (2/5)
               - [ ] Poor (1/5)
            
            2. **How easy is it to find the information you need?**
               - [ ] Very Easy
               - [ ] Easy
               - [ ] Moderate
               - [ ] Difficult
               - [ ] Very Difficult
            
            3. **How would you rate the quality of our documentation?**
               - [ ] Excellent
               - [ ] Good
               - [ ] Average
               - [ ] Below Average
               - [ ] Poor
            
            ### Standards Usage
            
            4. **Which standards have you implemented or referenced?** (Check all that apply)
               - [ ] Security & Compliance Standards
               - [ ] Coding Standards
               - [ ] DevOps Standards
               - [ ] Testing Standards
               - [ ] Documentation Standards
               - [ ] Cloud Native Standards
               - [ ] Database Standards
               - [ ] AI/ML Standards
               - [ ] Other: _________________
            
            5. **How successful were you in implementing these standards?**
               - [ ] Very Successful - Implemented fully with great results
               - [ ] Mostly Successful - Implemented with minor challenges
               - [ ] Partially Successful - Implemented some parts
               - [ ] Unsuccessful - Unable to implement effectively
               - [ ] Haven't attempted implementation yet
            
            6. **What was the biggest challenge in implementing our standards?**
               - [ ] Unclear documentation
               - [ ] Missing examples
               - [ ] Too complex for our environment
               - [ ] Lack of tool support
               - [ ] Organizational resistance
               - [ ] Time/resource constraints
               - [ ] Other: _________________
            
            ### Community Engagement
            
            7. **How do you primarily engage with the community?** (Check all that apply)
               - [ ] Reading documentation and standards
               - [ ] Contributing code or documentation
               - [ ] Participating in discussions
               - [ ] Reporting issues or bugs
               - [ ] Helping other community members
               - [ ] Following updates and releases
               - [ ] Other: _________________
            
            8. **How welcoming and inclusive do you find our community?**
               - [ ] Very Welcoming
               - [ ] Welcoming
               - [ ] Neutral
               - [ ] Somewhat Unwelcoming
               - [ ] Unwelcoming
            
            9. **How responsive are maintainers and community members to questions and contributions?**
               - [ ] Very Responsive (within hours)
               - [ ] Responsive (within 1-2 days)
               - [ ] Moderately Responsive (within a week)
               - [ ] Slow to Respond (more than a week)
               - [ ] Unresponsive
            
            ### Improvement Suggestions
            
            10. **What new standards or topics would you like to see covered?**
                *(Open text response)*
            
            11. **What tools or automation would be most helpful?**
                *(Open text response)*
            
            12. **How can we improve the contributor experience?**
                *(Open text response)*
            
            13. **What additional community features would you value?**
                - [ ] More interactive discussions
                - [ ] Video tutorials and webinars
                - [ ] Community office hours
                - [ ] Mentorship programs
                - [ ] Industry expert talks
                - [ ] Implementation workshops
                - [ ] Certification programs
                - [ ] Other: _________________
            
            ### About You
            
            14. **What best describes your role?** (Optional)
                - [ ] Software Developer
                - [ ] DevOps Engineer
                - [ ] Security Professional
                - [ ] Technical Lead/Architect
                - [ ] Engineering Manager
                - [ ] Product Manager
                - [ ] Student/Learner
                - [ ] Academic/Researcher
                - [ ] Other: _________________
            
            15. **How long have you been involved with this repository?**
                - [ ] First time visiting
                - [ ] Less than 3 months
                - [ ] 3-6 months
                - [ ] 6-12 months
                - [ ] 1-2 years
                - [ ] More than 2 years
            
            16. **Organization size** (Optional)
                - [ ] Individual/Personal projects
                - [ ] Startup (1-50 employees)
                - [ ] Small company (51-200 employees)
                - [ ] Medium company (201-1000 employees)
                - [ ] Large company (1000+ employees)
                - [ ] Government/Non-profit
                - [ ] Academic institution
            
            ### Final Thoughts
            
            17. **What do you value most about this repository and community?**
                *(Open text response)*
            
            18. **If you could change one thing about the repository or community, what would it be?**
                *(Open text response)*
            
            19. **How likely are you to recommend this repository to colleagues?**
                - [ ] Very Likely
                - [ ] Likely
                - [ ] Neutral
                - [ ] Unlikely
                - [ ] Very Unlikely
            
            20. **Any additional comments or suggestions?**
                *(Open text response)*
            
            ## Thank You!
            
            Your feedback is invaluable for improving our community. We review all responses and use them to guide our development priorities and community initiatives.
            
            **Survey Period**: This survey will remain open for 2 weeks. Results will be summarized and shared with the community.
            
            **Privacy**: Your responses help us improve the community. While the survey is public (GitHub issue), you can also provide anonymous feedback through other channels if preferred.
            
            ## Follow-up
            
            After collecting feedback, we will:
            1. Analyze responses and identify key themes
            2. Create an action plan based on feedback
            3. Share results with the community
            4. Implement improvements based on your suggestions
            5. Follow up on progress in the next quarter
            
            Thank you for being part of our community! 🚀
            `;
            } else if (feedbackType === 'post_contribution') {
              surveyTitle = '📝 Post-Contribution Feedback Request';
              labels.push('post-contribution-feedback');
              
              surveyBody = `
            # Post-Contribution Feedback
            
            Thank you for your recent contribution! We'd love to hear about your experience.
            
            ## Quick Feedback (2-3 minutes)
            
            1. **How was your contribution experience?**
               - [ ] Excellent
               - [ ] Good  
               - [ ] Average
               - [ ] Below Average
               - [ ] Poor
            
            2. **What went well?**
            
            3. **What could be improved?**
            
            4. **Would you contribute again?**
               - [ ] Definitely
               - [ ] Probably
               - [ ] Maybe
               - [ ] Probably Not
               - [ ] Definitely Not
            
            5. **Any other feedback?**
            
            Your feedback helps us improve the contribution experience for everyone!
            `;
            }
            
            return {
              title: surveyTitle,
              body: surveyBody,
              labels: labels
            };

      - name: Create feedback issue
        uses: actions/github-script@v7
        with:
          script: |
            const survey = ${{ steps.generate-survey.outputs.result }};
            const { owner, repo } = context.repo;
            
            const issue = await github.rest.issues.create({
              owner,
              repo,
              title: survey.title,
              body: survey.body,
              labels: survey.labels
            });
            
            console.log(`Created feedback survey: ${issue.data.html_url}`);
            
            return issue.data;

      - name: Pin feedback issue
        uses: actions/github-script@v7
        with:
          script: |
            const issue = ${{ steps.create-feedback-issue.outputs.result }};
            const { owner, repo } = context.repo;
            
            // Pin the issue for visibility
            await github.rest.issues.update({
              owner,
              repo,
              issue_number: issue.number,
              state: 'open'
            });
            
            console.log(`Feedback issue #${issue.number} created and configured`);

      - name: Notify community
        uses: actions/github-script@v7
        with:
          script: |
            const issue = ${{ steps.create-feedback-issue.outputs.result }};
            const { owner, repo } = context.repo;
            
            // Create a discussion to announce the feedback survey
            const discussionBody = `
            # 📊 Community Feedback Survey is Live!
            
            We've launched our quarterly community feedback survey to help improve the Standards Repository experience.
            
            ## Why Your Feedback Matters
            
            - Helps us prioritize improvements
            - Guides new feature development  
            - Improves community support
            - Shapes the future direction of our standards
            
            ## How to Participate
            
            🔗 **[Take the Survey](${issue.html_url})**
            
            The survey takes 5-10 minutes and covers:
            - Your experience with our standards
            - Community engagement feedback
            - Suggestions for improvements
            - Ideas for new features and content
            
            ## Survey Benefits
            
            All participants help us:
            - Build better standards and documentation
            - Create more helpful tools and automation
            - Improve the contributor experience
            - Strengthen our community
            
            ## Timeline
            
            - **Survey Open**: Now through 2 weeks
            - **Analysis**: Following week
            - **Results Sharing**: Within 1 month
            - **Action Planning**: Based on your feedback
            
            Your voice matters! Please take a few minutes to share your thoughts and help us build an even better community.
            
            Thank you! 🙏
            `;
            
            console.log('Community notification prepared');
            console.log('Discussion content:', discussionBody);